### ISSUE TITLE
`src` code not in GitHub

### ISSUE THREAD

**Issue by jlarmstrongiv** [nalgeon/sqlean.js#4]
I would like to switch from SQLite to sqlean.js 🎉 

In order to deploy successfully, I needed to patch and bundle SQLite in a specific way.  

I would like to apply those same patches to sqlean.js; however, the source code is unavailable and the distributed code is minified, making it very hard if not impossible to patch.

Would you release the source code on GitHub like [SQLite](https://github.com/sqlite/sqlite-wasm)?

**Comment by jlarmstrongiv** [comment]
I tried to just swap the wasm file from sqlean.js to the SQLite wasm package, but it failed with these errors:

```
Exception loading sqlite3 module: RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #0 module="env" function="__assert_fail" error: function import requires a callable). Build with -sASSERTIONS for more info.
    at abort (/Users/user/Desktop/projects/project/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:545:15)
    at <anonymous> (/Users/user/Desktop/projects/project/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:646:13)
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #0 module="env" function="__assert_fail" error: function import requires a callable). Build with -sASSERTIONS for more info.
    at abort (/Users/user/Desktop/projects/project/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:545:15)
    at <anonymous> (/Users/user/Desktop/projects/project/node_modules/@sqlite.org/sqlite-wasm/sqlite-wasm/jswasm/sqlite3-node.mjs:646:13)

Node.js v20.17.0
```

Having the `src/sqlean.mjs` available would be extremely helpful.

**Comment by nalgeon** [comment]
The build process is currently manual, and I don't plan to commit the source code.
