### ISSUE TITLE
Unable to run the wasm version in other runtimes

### ISSUE THREAD

**Issue by jlarmstrongiv** [nalgeon/sqlean.js#7]
```
Exception loading sqlite3 module: TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13 {
  [cause]: Error: not implemented... yet...
      at makeNetworkError (node:internal/deps/undici/undici:8961:35)
      at schemeFetch (node:internal/deps/undici/undici:10356:34)
      at node:internal/deps/undici/undici:10205:26
      at mainFetch (node:internal/deps/undici/undici:10224:11)
      at fetching (node:internal/deps/undici/undici:10172:7)
      at fetch (node:internal/deps/undici/undici:10041:20)
      at fetch (node:internal/deps/undici/undici:13176:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at lr (file:///Users/user/~Desktop/projects/project/node_modules/@antonz/sqlean/dist/sqlean.mjs:1:5051)
      at cr (file:///Users/user/~Desktop/projects/project/node_modules/@antonz/sqlean/dist/sqlean.mjs:1:5619)
}
node:internal/modules/run_main:129
    triggerUncaughtException(
    ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13 {
  [cause]: Error: not implemented... yet...
      at makeNetworkError (node:internal/deps/undici/undici:8961:35)
      at schemeFetch (node:internal/deps/undici/undici:10356:34)
      at node:internal/deps/undici/undici:10205:26
      at mainFetch (node:internal/deps/undici/undici:10224:11)
      at fetching (node:internal/deps/undici/undici:10172:7)
      at fetch (node:internal/deps/undici/undici:10041:20)
      at fetch (node:internal/deps/undici/undici:13176:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:72:12)
      at lr (file:///Users/user/~Desktop/projects/project/node_modules/@antonz/sqlean/dist/sqlean.mjs:1:5051)
      at cr (file:///Users/user/~Desktop/projects/project/node_modules/@antonz/sqlean/dist/sqlean.mjs:1:5619)
}

Node.js v20.17.0
```

It is possible to run the wasm version of SQLite in other runtimes with https://github.com/sqlite/sqlite-wasm/blob/main/sqlite-wasm/jswasm/sqlite3-node.mjs

The main benefit of using wasm is better cross-platform compatibility and better runtime support across various web-interoperable runtimes including Node.js, browsers, Cloudflare Workers, Deno, Bun, and others.

**Comment by nalgeon** [comment]
This package is provided as-is, and I have no plans to test or support other runtimes. Sorry about that.
